# Matrix Algebra

### By Vivian Zeng, 08/19/2020

#### 1.Load the Ames Housing dataset in Python. Print the first few rows of this data frame.

In [2]:
import numpy as np
import pandas as pd

ames = pd.read_csv('ames.csv')
ames.head(5)

MS_SubClass                 MS_Zoning  \
0  One_Story_1946_and_Newer_All_Styles   Residential_Low_Density   
1  One_Story_1946_and_Newer_All_Styles  Residential_High_Density   
2  One_Story_1946_and_Newer_All_Styles   Residential_Low_Density   
3  One_Story_1946_and_Newer_All_Styles   Residential_Low_Density   
4             Two_Story_1946_and_Newer   Residential_Low_Density   

   Lot_Frontage  Lot_Area Street            Alley           Lot_Shape  \
0           141     31770   Pave  No_Alley_Access  Slightly_Irregular   
1            80     11622   Pave  No_Alley_Access             Regular   
2            81     14267   Pave  No_Alley_Access  Slightly_Irregular   
3            93     11160   Pave  No_Alley_Access             Regular   
4            74     13830   Pave  No_Alley_Access  Slightly_Irregular   

  Land_Contour Utilities Lot_Config  ...            Fence Misc_Feature  \
0          Lvl    AllPub     Corner  ...         No_Fence         None   
1          Lvl    AllPub     Inside  ...  Minimum_Privacy         None   
2          Lvl    AllPub     Corner  ...         No_Fence         Gar2   
3          Lvl    AllPub     Corner  ...         No_Fence         None   
4          Lvl    AllPub     Inside  ...  Minimum_Privacy         None   

  Misc_Val Mo_Sold Year_Sold Sale_Type Sale_Condition Sale_Price  Longitude  \
0        0       5      2010       WD          Normal     215000 -93.619754   
1        0       6      2010       WD          Normal     105000 -93.619756   
2    12500       6      2010       WD          Normal     172000 -93.619387   
3        0       4      2010       WD          Normal     244000 -93.617320   
4        0       3      2010       WD          Normal     189900 -93.638933   

    Latitude  
0  42.054035  
1  42.053014  
2  42.052659  
3  42.051245  
4  42.060899  

[5 rows x 81 columns]

#### 2. Create a matrix with the following quantitative variables and call this “X”: Lot_Area, Longitude, Latitude, Year_Built, First_Flr_SF. Print the first few rows of this matrix. 

In [13]:
df=ames[['Lot_Area', 'Longitude', 'Latitude', 'Year_Built', 'First_Flr_SF']].dropna()
X=df.values
print(X[:5,])

[[31770.          -93.619754     42.054035   1960.         1656.       ]
 [11622.          -93.619756     42.053014   1961.          896.       ]
 [14267.          -93.6193873    42.052659   1958.         1329.       ]
 [11160.          -93.61732      42.051245   1968.         2110.       ]
 [13830.          -93.638933     42.060899   1997.          928.       ]]


#### 3. What are the dimensions of the matrix? Using our usual notation, what are n and p? 

In [6]:
X.shape
n,p=X.shape
print('n is ', X.shape[0])
print('p is ', X.shape[1])

n is  2930
p is  5


#### 4. In general, we will want to standardize our data before fitting it with a model. We will do this by transforming the data so that each variable has mean 0 and standard deviation 1. 
#### 4.1 Calculate the mean and standard deviation for each column. Store each of these as p-dimensional vectors. Print both of these vectors.

In [11]:
means=np.mean(X, axis=0)
sds=np.std(X, axis =0)
print('mean is ', means)
print('standard deviation is', sds)

mean is  [10147.921843     -93.6428969     42.03448223  1971.35631399
  1159.55767918]
standard deviation is [7.87867293e+03 2.56951849e-02 1.84069300e-02 3.02401989e+01
 3.91824004e+02]


#### 4.2 Create a matrix “M” with the same dimensions as X, but each value is the mean of the corresponding column in X. That is, every element in column 1 of M is the mean of column 1 in X, and so on. Print the first few rows of M.

In [12]:
M=means+np.zeros((n,p))
print(M[:5,])

[[10147.921843     -93.6428969     42.03448223  1971.35631399
   1159.55767918]
 [10147.921843     -93.6428969     42.03448223  1971.35631399
   1159.55767918]
 [10147.921843     -93.6428969     42.03448223  1971.35631399
   1159.55767918]
 [10147.921843     -93.6428969     42.03448223  1971.35631399
   1159.55767918]
 [10147.921843     -93.6428969     42.03448223  1971.35631399
   1159.55767918]]


#### 4.3 Create a p*p diagonal matrix “S_inv” where diagonal element j, is 1/standard deviation of column j of X. Print the first few rows of S_inv.

In [15]:
S_inv=np.diag(1/sds)
print(S_inv[:5,])
S_inv.shape

[[1.26924929e-04 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 3.89177974e+01 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.43273646e+01 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.30685656e-02
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  2.55216625e-03]]


(5, 5)

#### 4.4 Now we can standardize by first subtracting the mean from X, and dividing by the standard deviation of each column Z = (X-M) S_inv. Print the first few rows of Z.

In [16]:
Z = (X-M)@S_inv
print(Z[:5,])

[[ 2.74438073  0.90067064  1.06225025 -0.37553701  1.26700334]
 [ 0.18709726  0.9005928   1.00678201 -0.34246845 -0.67264301]
 [ 0.5228137   0.91494179  0.9874958  -0.44167415  0.43244497]
 [ 0.12845795  0.99539656  0.9106769  -0.11098849  2.42568682]
 [ 0.46734751  0.1542662   1.43515328  0.84799991 -0.59097369]]


#### 4.5 Check that each column of the new matrix Z has mean 0 and standard deviation 1. (Because of numerical reasons, these might not be exactly the same. You can use np.isclose to check if they are close enough). Print the first few rows of Z.

In [17]:
np.isclose(Z.mean(axis=0), np.zeros(p))

array([ True,  True,  True,  True,  True])

In [18]:
np.isclose(Z.std(axis=0), np.ones(p)).all()

True

#### 5. Using our standardized matrix of predictors, Z, we want to calculate inverse of Z’Z. In statistics, this matrix is used for estimating the coefficients and standard errors in linear regression. 

#### 5.1 Compute Z’Z and call this “ZTZ”. Check that the dimensions are p by p, by printing the dimensions. Also print the matrix ZTZ.

In [19]:
ZTZ=Z.T@Z
ZTZ.shape

(5, 5)

In [20]:
print(ZTZ)

[[ 2930.          -288.9341701   -107.32248949    68.14739115
    973.44849384]
 [ -288.9341701   2930.            88.1608279  -1246.91354873
   -398.12091769]
 [ -107.32248949    88.1608279   2930.           736.59264511
    380.11685346]
 [   68.14739115 -1246.91354873   736.59264511  2930.
    909.65525769]
 [  973.44849384  -398.12091769   380.11685346   909.65525769
   2930.        ]]


#### 5.2 Compute the inverse of this and call it “ZTZ_inv”. Check that this worked by multiplying the result by ZTZ. You should get the identity matrix back. Print the result of the code you used to check this.

In [21]:
ZTZ_inv=np.linalg.inv(ZTZ)

In [22]:
np.isclose(ZTZ_inv@ZTZ, np.identity(p)) 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

#### 6. We can use the matrix algebra operations we’ve performed so far to fit a linear regression model to predict Sale_Price from the standardized predictors, Z. 

#### 6.1 Create a numpy vector from the variable Sale_Price. Print the first few elements of this vector.

In [23]:
Y=ames['Sale_Price'].values
print(Y[:5])

[215000 105000 172000 244000 189900]


#### 6.2 Standardize this vector (subtract mean and divide standard deviation), and call it “y”. Print the first few elements of y.

In [24]:
y=(Y-np.mean(Y))/np.std(Y)
print(y[:5])

[ 0.42822875 -0.94895652 -0.11012549  0.79130487  0.11398011]


#### 6.3 Compute (ZTZ_inv)Z’y and call this “beta”. These are the regression coefficients we would get from linear regression (assuming no intercept). Print the vector, beta.

In [25]:
beta=ZTZ_inv@Z.T@y
print(beta)

[ 0.11196846 -0.02687706  0.14498226  0.36901981  0.44744846]


#### 6.4 Check that these coefficients are correct by fitting a linear regression model with scikit-learn,  and print the estimated coefficients with the code below.
#### from sklearn.linear_model import LinearRegression
#### reg = LinearRegression(fit_intercept=False)
#### reg.fit(Z, y)
#### print(reg.coef_)


In [26]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression(fit_intercept=False)
reg.fit(Z, y)
print(reg.coef_)

[ 0.11196846 -0.02687706  0.14498226  0.36901981  0.44744846]


#### 7. Explore the eigendecomposition of the matrix ZTZ. 
#### 7.1 Calculate the eigendecomposition of matrix ZTZ and store the eigenvalues as “v” and the matrix of eigenvectors as “V”. Print v and V.

In [28]:
v, V = np.linalg.eig(ZTZ)
print('v is ', v)
print('V is ', V)

v is  [5080.60059045 1311.08782029 1870.84278655 3365.20081099 3022.2679917 ]
V is  [[ 0.30432414 -0.26793871  0.54338809 -0.72435383  0.12504629]
 [-0.46908408 -0.50346978 -0.32054606 -0.14162583  0.63535081]
 [ 0.25989882  0.23795972  0.42375221  0.45931627  0.69662787]
 [ 0.59075036 -0.6931927  -0.16774914  0.35841369 -0.11788869]
 [ 0.52039749  0.37092597 -0.62791233 -0.34032608  0.28549017]]


#### 7.2 Confirm that V is orthogonal. Print the result of the code you used to check this. 

In [29]:
np.isclose(0.0, np.dot(V[:, 0], V[:,1]))

True

#### 7.3 Use the formula for the eigen decomposition to recreate ZTZ using only v and V. Print the matrix and check that is the same as the ZTZ matrix you printed above.

In [30]:
np.isclose(V @ np.diag(v) @ V.T, ZTZ)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])